package main

// CALIBRATION, part 1 of 2: the detector is checked against a known-good case
// before it is ever pointed at the log, and the check is COUNTED.
//
// The known-good case is RFC 6962's own construction. This file contains a
// SECOND, INDEPENDENT implementation of the specification -- the recursive
// definitional form the RFC writes out in section 2.1 (MTH), 2.1.1 (PATH) and
// 2.1.2 (PROOF/SUBPROOF) -- and cross-checks the iterative verifier in
// merkle.go against it over every (leaf, tree size) pair up to size 16.
//
// Why two implementations rather than a table of expected hashes: a table
// copied from memory is a citation nobody can check, and a table generated by
// the code under test proves that the code agrees with itself. The recursive
// form here is a transcription of the RFC's own equations and shares no line
// with the iterative form it judges.
//
// Every test reports COUNTS, and every positive count is paired with a
// mutation count, so that a later "the verifier found nothing wrong" is
// evidence rather than silence.

import (
	"crypto/sha256"
	"fmt"
	"testing"
)

// ---- the reference implementation: RFC 6962, transcribed -------------------

func refMTH(d [][]byte) [32]byte {
	switch len(d) {
	case 0:
		return sha256.Sum256(nil)
	case 1:
		return LeafHashRef(d[0])
	}
	k := largestPowerOfTwoBelow(len(d))
	return nodeHashRef(refMTH(d[:k]), refMTH(d[k:]))
}

// Deliberately re-derived rather than calling merkle.go, so the cross-check is
// between two implementations and not between one implementation and itself.
func LeafHashRef(b []byte) [32]byte {
	return sha256.Sum256(append([]byte{0x00}, b...))
}

func nodeHashRef(l, r [32]byte) [32]byte {
	buf := make([]byte, 0, 65)
	buf = append(buf, 0x01)
	buf = append(buf, l[:]...)
	buf = append(buf, r[:]...)
	return sha256.Sum256(buf)
}

func largestPowerOfTwoBelow(n int) int {
	k := 1
	for k<<1 < n {
		k <<= 1
	}
	return k
}

// The RFC writes its paths as list concatenation. `append` on a slice returned
// by a recursive call can reuse that call's backing array, which silently
// corrupts a sibling branch's result. Concatenating into a fresh slice costs
// nothing here and removes the whole class.
func cat(a [][32]byte, b [32]byte) [][32]byte {
	out := make([][32]byte, len(a)+1)
	copy(out, a)
	out[len(a)] = b
	return out
}

// PATH(m, D[n]) -- RFC 6962 section 2.1.1.
func refPATH(m int, d [][]byte) [][32]byte {
	if len(d) == 1 && m == 0 {
		return nil
	}
	k := largestPowerOfTwoBelow(len(d))
	if m < k {
		return cat(refPATH(m, d[:k]), refMTH(d[k:]))
	}
	return cat(refPATH(m-k, d[k:]), refMTH(d[:k]))
}

// PROOF(m, D[n]) -- RFC 6962 section 2.1.2.
func refPROOF(m int, d [][]byte) [][32]byte { return refSUBPROOF(m, d, true) }

func refSUBPROOF(m int, d [][]byte, b bool) [][32]byte {
	if m == len(d) {
		if b {
			return nil
		}
		return [][32]byte{refMTH(d)}
	}
	k := largestPowerOfTwoBelow(len(d))
	if m <= k {
		return cat(refSUBPROOF(m, d[:k], b), refMTH(d[k:]))
	}
	return cat(refSUBPROOF(m-k, d[k:], false), refMTH(d[:k]))
}

func leaves(n int) [][]byte {
	out := make([][]byte, n)
	for i := range out {
		// Distinct, and deliberately of varying length, so a bug that
		// concatenates rather than hashes shows up.
		out[i] = []byte(fmt.Sprintf("txl-leaf-%d-%s", i, make([]byte, i%7)))
	}
	return out
}

// ---- the tests -------------------------------------------------------------

const maxSize = 16

func TestInclusionAgainstRFC6962Reference(t *testing.T) {
	verified, mutantsRejected, mutantsAccepted := 0, 0, 0
	for n := 1; n <= maxSize; n++ {
		d := leaves(n)
		root := refMTH(d)
		for m := 0; m < n; m++ {
			path := refPATH(m, d)
			got, err := RootFromInclusionProof(LeafHash(d[m]), uint64(m), uint64(n), path)
			if err != nil {
				t.Fatalf("size %d index %d: verifier refused a VALID path: %v", n, m, err)
			}
			if got != root {
				t.Fatalf("size %d index %d: recomputed %x, RFC reference MTH is %x", n, m, got, root)
			}
			verified++

			// MUTATION. One bit flipped in one sibling hash of an otherwise
			// valid path. If this still reproduces the root the verifier is
			// not reading the path at all, and every PASS above is decoration.
			for j := range path {
				mut := make([][32]byte, len(path))
				copy(mut, path)
				mut[j][0] ^= 0x01
				bad, err := RootFromInclusionProof(LeafHash(d[m]), uint64(m), uint64(n), mut)
				if err != nil || bad != root {
					mutantsRejected++
				} else {
					mutantsAccepted++
					t.Errorf("size %d index %d: a path with hash %d corrupted STILL reproduced the root", n, m, j)
				}
			}

			// MUTATION. One bit flipped in the leaf itself -- the tampered
			// entry the demo's `tampered-entry` control executes against the
			// live log, exercised here at unit level over every index.
			bl := LeafHash(d[m])
			bl[31] ^= 0x80
			bad, err := RootFromInclusionProof(bl, uint64(m), uint64(n), path)
			if err != nil || bad != root {
				mutantsRejected++
			} else {
				mutantsAccepted++
				t.Errorf("size %d index %d: a TAMPERED leaf still reproduced the root", n, m)
			}
		}
	}
	t.Logf("CALIBRATION inclusion: sizes 1..%d, valid (leaf,size) pairs verified: %d, "+
		"mutants rejected: %d, mutants accepted: %d", maxSize, verified, mutantsRejected, mutantsAccepted)
	if verified == 0 || mutantsRejected == 0 {
		t.Fatalf("the calibration itself was vacuous: verified=%d mutantsRejected=%d", verified, mutantsRejected)
	}
}

func TestConsistencyAgainstRFC6962Reference(t *testing.T) {
	verified, mutantsRejected, mutantsAccepted := 0, 0, 0
	for n := 1; n <= maxSize; n++ {
		d := leaves(n)
		secondRoot := refMTH(d)
		for m := 1; m <= n; m++ {
			firstRoot := refMTH(d[:m])
			proof := refPROOF(m, d)
			if err := VerifyConsistency(uint64(m), uint64(n), proof, firstRoot, secondRoot); err != nil {
				t.Fatalf("sizes %d->%d: verifier refused a VALID consistency proof: %v", m, n, err)
			}
			verified++

			// MUTATION. The earlier root is the thing a log that rewrote
			// history would have to lie about. Flip one bit in it.
			br := firstRoot
			br[0] ^= 0x01
			if err := VerifyConsistency(uint64(m), uint64(n), proof, br, secondRoot); err != nil {
				mutantsRejected++
			} else {
				mutantsAccepted++
				t.Errorf("sizes %d->%d: a WRONG earlier root was accepted as consistent", m, n)
			}

			// MUTATION. Flip a bit in each proof node in turn.
			for j := range proof {
				mut := make([][32]byte, len(proof))
				copy(mut, proof)
				mut[j][5] ^= 0x40
				if err := VerifyConsistency(uint64(m), uint64(n), mut, firstRoot, secondRoot); err != nil {
					mutantsRejected++
				} else {
					mutantsAccepted++
					t.Errorf("sizes %d->%d: a corrupted proof node %d was accepted", m, n, j)
				}
			}
		}
	}
	t.Logf("CALIBRATION consistency: sizes 1..%d, valid (first,second) pairs verified: %d, "+
		"mutants rejected: %d, mutants accepted: %d", maxSize, verified, mutantsRejected, mutantsAccepted)
	if verified == 0 || mutantsRejected == 0 {
		t.Fatalf("the calibration itself was vacuous: verified=%d mutantsRejected=%d", verified, mutantsRejected)
	}
}

// The domain-separation prefixes are the difference between a Merkle tree and
// a hash chain that can be re-parsed. Asserted, because their absence is
// invisible: every root still matches every proof, and only a second-preimage
// attack notices.
func TestDomainSeparation(t *testing.T) {
	a := LeafHash([]byte("x"))
	if a == sha256.Sum256([]byte("x")) {
		t.Fatal("leaf hashing has no 0x00 prefix")
	}
	l, r := LeafHash([]byte("l")), LeafHash([]byte("r"))
	n := NodeHash(l, r)
	if n == sha256.Sum256(append(l[:], r[:]...)) {
		t.Fatal("node hashing has no 0x01 prefix")
	}
	// A leaf whose bytes ARE a node's preimage must not hash to that node.
	forged := LeafHash(append(l[:], r[:]...))
	if forged == n {
		t.Fatal("a leaf collided with an interior node: domain separation is absent")
	}
	t.Logf("CALIBRATION domain separation: 3 distinctions asserted, 0 collisions")
}

// An empty log's root is a value, not a claim. If a verifier accepts an
// inclusion proof against tree size 0 then "your entry is in the empty log"
// verifies, which is the shape of every gate that passes because it had
// nothing to check.
func TestEmptyTreeRejectsInclusion(t *testing.T) {
	if _, err := RootFromInclusionProof(LeafHash([]byte("x")), 0, 0, nil); err == nil {
		t.Fatal("an inclusion proof against a tree of size 0 was accepted")
	}
	want := sha256.Sum256(nil)
	if EmptyRootHash() != want {
		t.Fatalf("empty root is %x, RFC 6962 says SHA-256() = %x", EmptyRootHash(), want)
	}
	t.Logf("CALIBRATION empty tree: inclusion refused, MTH({}) = %x", EmptyRootHash())
}
